# Makefile.in generated by automake 1.7.4 from Makefile.am.
# src2/Makefile.  Generated from Makefile.in by configure.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



srcdir = .
top_srcdir = ..

pkgdatadir = $(datadir)/mps
pkglibdir = $(libdir)/mps
pkgincludedir = $(includedir)/mps
top_builddir = ..

am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_triplet = i686-pc-linux-gnu
ACLOCAL = ${SHELL} /home/MPS/missing --run aclocal-1.7
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/MPS/missing --run tar
AUTOCONF = ${SHELL} /home/MPS/missing --run autoconf
AUTOHEADER = ${SHELL} /home/MPS/missing --run autoheader
AUTOMAKE = ${SHELL} /home/MPS/missing --run automake-1.7
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3

CXXFLAGS = -g
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = grep -E
EXEEXT = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/MPS/missing --run makeinfo
OBJEXT = o
PACKAGE = mps
PACKAGE_BUGREPORT = bbutton@agilestl.com
PACKAGE_NAME = MPS
PACKAGE_STRING = MPS 0.1
PACKAGE_TARNAME = mps
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.1
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_RANLIB = ranlib
ac_ct_STRIP = strip
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/MPS/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
lib_LIBRARIES = libMPS2.a

noinst_PROGRAMS = TestDriver PrintToFile

bin_PROGRAMS = CSS

CSS_SOURCES = main.cc

PrintToFile_SOURCES = PrintToFile.cc

TestDriver_SOURCES = ConveyerBeltTest.cc		\
				DBLoggerTest.cc			\
				DBPackageFactoryTest.cc		\
				EventDrivenPrinterTest.cc	\
				EventDrivenSPMTest.cc		\
				LabelFieldTest.cc		\
				LabelFormatterTest.cc		\
				MaxicodeLabelDataTest.cc	\
				MPSTest.cc			\
				PLCTest.cc			\
				ParallelPortPrinterTest.cc	\
				ParallelPortTest.cc		\
				ProducerConsumerQueueTest.cc	\
				RTCEncoderTest.cc		\
				RunnableTest.cc			\
				SerialPortTest.cc		\
				SPMTest.cc			\
				SystemFacadeTest.cc		\
				TimerTest.cc			\
				UtilsTest.cc			\
				TestDriver.cc


LDADD = libMPS2.a
AM_LDFLAGS = -L../lib/CppUnitLite/TestHarness -lCppUnitLite -L/usr/local/lib -lsqlplus -lmysqlclient_r -lboost_date_time -lboost_thread -lboost_regex -pthread

libMPS2_a_SOURCES = BarCodeReader.cc			\
				ConveyerBelt.cc				\
				ConveyerBeltIF.cc			\
				CreationScanMPSAdapter.cc		\
				DBLogger.cc				\
				DBPackageFactory.cc			\
				ErrorConsumer.cc			\
				DefaultRunnable.cc			\
				EventDrivenBarCodeReader.cc		\
				EventDrivenParallelPortPrinter.cc	\
				EventDrivenSPM.cc			\
				HardwareParallelPort.cc			\
				LabelField.cc				\
				LabelFormatter.cc			\
				Logger.cc				\
				LoggingConveyerBelt.cc			\
				MaxicodeLabelData.cc			\
				MPS.cc					\
				PLC.cc					\
				Package.cc				\
				PackageControls.cc			\
				ParallelPort.cc				\
				ParallelPortPrinter.cc			\
				PollConsumer.cc				\
				RealPackage.cc				\
				RemotePLC.cc				\
				RTCEncoder.cc				\
				Runnable.cc				\
				SerialPort.cc				\
				SimpleBarCodeReader.cc			\
				SPM.cc					\
				SystemFacade.cc				\
				ThreadManager.cc			\
				Utils.cc				\
				VerifyScanMPSAdapter.cc



#CSS_SOURCES		=	main.cc
AM_CPPFLAGS = -I.. -I../lib/CppUnitLite/TestHarness -I/usr/include/mysql -I/usr/local/include -Wno-deprecated -pthread -W
subdir = src2
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(lib_LIBRARIES)

libMPS2_a_AR = $(AR) cru
libMPS2_a_LIBADD =
am_libMPS2_a_OBJECTS = BarCodeReader.$(OBJEXT) ConveyerBelt.$(OBJEXT) \
	ConveyerBeltIF.$(OBJEXT) CreationScanMPSAdapter.$(OBJEXT) \
	DBLogger.$(OBJEXT) DBPackageFactory.$(OBJEXT) \
	ErrorConsumer.$(OBJEXT) DefaultRunnable.$(OBJEXT) \
	EventDrivenBarCodeReader.$(OBJEXT) \
	EventDrivenParallelPortPrinter.$(OBJEXT) \
	EventDrivenSPM.$(OBJEXT) HardwareParallelPort.$(OBJEXT) \
	LabelField.$(OBJEXT) LabelFormatter.$(OBJEXT) Logger.$(OBJEXT) \
	LoggingConveyerBelt.$(OBJEXT) MaxicodeLabelData.$(OBJEXT) \
	MPS.$(OBJEXT) PLC.$(OBJEXT) Package.$(OBJEXT) \
	PackageControls.$(OBJEXT) ParallelPort.$(OBJEXT) \
	ParallelPortPrinter.$(OBJEXT) PollConsumer.$(OBJEXT) \
	RealPackage.$(OBJEXT) RemotePLC.$(OBJEXT) RTCEncoder.$(OBJEXT) \
	Runnable.$(OBJEXT) SerialPort.$(OBJEXT) \
	SimpleBarCodeReader.$(OBJEXT) SPM.$(OBJEXT) \
	SystemFacade.$(OBJEXT) ThreadManager.$(OBJEXT) Utils.$(OBJEXT) \
	VerifyScanMPSAdapter.$(OBJEXT)
libMPS2_a_OBJECTS = $(am_libMPS2_a_OBJECTS)
bin_PROGRAMS = CSS$(EXEEXT)
noinst_PROGRAMS = TestDriver$(EXEEXT) PrintToFile$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)

am_CSS_OBJECTS = main.$(OBJEXT)
CSS_OBJECTS = $(am_CSS_OBJECTS)
CSS_LDADD = $(LDADD)
CSS_DEPENDENCIES = libMPS2.a
CSS_LDFLAGS =
am_PrintToFile_OBJECTS = PrintToFile.$(OBJEXT)
PrintToFile_OBJECTS = $(am_PrintToFile_OBJECTS)
PrintToFile_LDADD = $(LDADD)
PrintToFile_DEPENDENCIES = libMPS2.a
PrintToFile_LDFLAGS =
am_TestDriver_OBJECTS = ConveyerBeltTest.$(OBJEXT) \
	DBLoggerTest.$(OBJEXT) DBPackageFactoryTest.$(OBJEXT) \
	EventDrivenPrinterTest.$(OBJEXT) EventDrivenSPMTest.$(OBJEXT) \
	LabelFieldTest.$(OBJEXT) LabelFormatterTest.$(OBJEXT) \
	MaxicodeLabelDataTest.$(OBJEXT) MPSTest.$(OBJEXT) \
	PLCTest.$(OBJEXT) ParallelPortPrinterTest.$(OBJEXT) \
	ParallelPortTest.$(OBJEXT) ProducerConsumerQueueTest.$(OBJEXT) \
	RTCEncoderTest.$(OBJEXT) RunnableTest.$(OBJEXT) \
	SerialPortTest.$(OBJEXT) SPMTest.$(OBJEXT) \
	SystemFacadeTest.$(OBJEXT) TimerTest.$(OBJEXT) \
	UtilsTest.$(OBJEXT) TestDriver.$(OBJEXT)
TestDriver_OBJECTS = $(am_TestDriver_OBJECTS)
TestDriver_LDADD = $(LDADD)
TestDriver_DEPENDENCIES = libMPS2.a
TestDriver_LDFLAGS =

DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
DEP_FILES = ./$(DEPDIR)/BarCodeReader.Po \
	./$(DEPDIR)/ConveyerBelt.Po \
	./$(DEPDIR)/ConveyerBeltIF.Po \
	./$(DEPDIR)/ConveyerBeltTest.Po \
	./$(DEPDIR)/CreationScanMPSAdapter.Po \
	./$(DEPDIR)/DBLogger.Po ./$(DEPDIR)/DBLoggerTest.Po \
	./$(DEPDIR)/DBPackageFactory.Po \
	./$(DEPDIR)/DBPackageFactoryTest.Po \
	./$(DEPDIR)/DefaultRunnable.Po \
	./$(DEPDIR)/ErrorConsumer.Po \
	./$(DEPDIR)/EventDrivenBarCodeReader.Po \
	./$(DEPDIR)/EventDrivenParallelPortPrinter.Po \
	./$(DEPDIR)/EventDrivenPrinterTest.Po \
	./$(DEPDIR)/EventDrivenSPM.Po \
	./$(DEPDIR)/EventDrivenSPMTest.Po \
	./$(DEPDIR)/HardwareParallelPort.Po \
	./$(DEPDIR)/LabelField.Po \
	./$(DEPDIR)/LabelFieldTest.Po \
	./$(DEPDIR)/LabelFormatter.Po \
	./$(DEPDIR)/LabelFormatterTest.Po \
	./$(DEPDIR)/Logger.Po \
	./$(DEPDIR)/LoggingConveyerBelt.Po \
	./$(DEPDIR)/MPS.Po ./$(DEPDIR)/MPSTest.Po \
	./$(DEPDIR)/MaxicodeLabelData.Po \
	./$(DEPDIR)/MaxicodeLabelDataTest.Po \
	./$(DEPDIR)/PLC.Po ./$(DEPDIR)/PLCTest.Po \
	./$(DEPDIR)/Package.Po \
	./$(DEPDIR)/PackageControls.Po \
	./$(DEPDIR)/ParallelPort.Po \
	./$(DEPDIR)/ParallelPortPrinter.Po \
	./$(DEPDIR)/ParallelPortPrinterTest.Po \
	./$(DEPDIR)/ParallelPortTest.Po \
	./$(DEPDIR)/PollConsumer.Po \
	./$(DEPDIR)/PrintToFile.Po \
	./$(DEPDIR)/ProducerConsumerQueueTest.Po \
	./$(DEPDIR)/RTCEncoder.Po \
	./$(DEPDIR)/RTCEncoderTest.Po \
	./$(DEPDIR)/RealPackage.Po ./$(DEPDIR)/RemotePLC.Po \
	./$(DEPDIR)/Runnable.Po ./$(DEPDIR)/RunnableTest.Po \
	./$(DEPDIR)/SPM.Po ./$(DEPDIR)/SPMTest.Po \
	./$(DEPDIR)/SerialPort.Po \
	./$(DEPDIR)/SerialPortTest.Po \
	./$(DEPDIR)/SimpleBarCodeReader.Po \
	./$(DEPDIR)/SystemFacade.Po \
	./$(DEPDIR)/SystemFacadeTest.Po \
	./$(DEPDIR)/TestDriver.Po \
	./$(DEPDIR)/ThreadManager.Po \
	./$(DEPDIR)/TimerTest.Po ./$(DEPDIR)/Utils.Po \
	./$(DEPDIR)/UtilsTest.Po \
	./$(DEPDIR)/VerifyScanMPSAdapter.Po \
	./$(DEPDIR)/main.Po
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(libMPS2_a_SOURCES) $(CSS_SOURCES) \
	$(PrintToFile_SOURCES) $(TestDriver_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(libMPS2_a_SOURCES) $(CSS_SOURCES) $(PrintToFile_SOURCES) $(TestDriver_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  src2/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)

AR = ar
libLIBRARIES_INSTALL = $(INSTALL_DATA)
install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f="`echo $$p | sed -e 's|^.*/||'`"; \
	    echo " $(libLIBRARIES_INSTALL) $$p $(DESTDIR)$(libdir)/$$f"; \
	    $(libLIBRARIES_INSTALL) $$p $(DESTDIR)$(libdir)/$$f; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    p="`echo $$p | sed -e 's|^.*/||'`"; \
	    echo " $(RANLIB) $(DESTDIR)$(libdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  p="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(libdir)/$$p"; \
	  rm -f $(DESTDIR)$(libdir)/$$p; \
	done

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
libMPS2.a: $(libMPS2_a_OBJECTS) $(libMPS2_a_DEPENDENCIES) 
	-rm -f libMPS2.a
	$(libMPS2_a_AR) libMPS2.a $(libMPS2_a_OBJECTS) $(libMPS2_a_LIBADD)
	$(RANLIB) libMPS2.a
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
CSS$(EXEEXT): $(CSS_OBJECTS) $(CSS_DEPENDENCIES) 
	@rm -f CSS$(EXEEXT)
	$(CXXLINK) $(CSS_LDFLAGS) $(CSS_OBJECTS) $(CSS_LDADD) $(LIBS)
PrintToFile$(EXEEXT): $(PrintToFile_OBJECTS) $(PrintToFile_DEPENDENCIES) 
	@rm -f PrintToFile$(EXEEXT)
	$(CXXLINK) $(PrintToFile_LDFLAGS) $(PrintToFile_OBJECTS) $(PrintToFile_LDADD) $(LIBS)
TestDriver$(EXEEXT): $(TestDriver_OBJECTS) $(TestDriver_DEPENDENCIES) 
	@rm -f TestDriver$(EXEEXT)
	$(CXXLINK) $(TestDriver_LDFLAGS) $(TestDriver_OBJECTS) $(TestDriver_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/BarCodeReader.Po
include ./$(DEPDIR)/ConveyerBelt.Po
include ./$(DEPDIR)/ConveyerBeltIF.Po
include ./$(DEPDIR)/ConveyerBeltTest.Po
include ./$(DEPDIR)/CreationScanMPSAdapter.Po
include ./$(DEPDIR)/DBLogger.Po
include ./$(DEPDIR)/DBLoggerTest.Po
include ./$(DEPDIR)/DBPackageFactory.Po
include ./$(DEPDIR)/DBPackageFactoryTest.Po
include ./$(DEPDIR)/DefaultRunnable.Po
include ./$(DEPDIR)/ErrorConsumer.Po
include ./$(DEPDIR)/EventDrivenBarCodeReader.Po
include ./$(DEPDIR)/EventDrivenParallelPortPrinter.Po
include ./$(DEPDIR)/EventDrivenPrinterTest.Po
include ./$(DEPDIR)/EventDrivenSPM.Po
include ./$(DEPDIR)/EventDrivenSPMTest.Po
include ./$(DEPDIR)/HardwareParallelPort.Po
include ./$(DEPDIR)/LabelField.Po
include ./$(DEPDIR)/LabelFieldTest.Po
include ./$(DEPDIR)/LabelFormatter.Po
include ./$(DEPDIR)/LabelFormatterTest.Po
include ./$(DEPDIR)/Logger.Po
include ./$(DEPDIR)/LoggingConveyerBelt.Po
include ./$(DEPDIR)/MPS.Po
include ./$(DEPDIR)/MPSTest.Po
include ./$(DEPDIR)/MaxicodeLabelData.Po
include ./$(DEPDIR)/MaxicodeLabelDataTest.Po
include ./$(DEPDIR)/PLC.Po
include ./$(DEPDIR)/PLCTest.Po
include ./$(DEPDIR)/Package.Po
include ./$(DEPDIR)/PackageControls.Po
include ./$(DEPDIR)/ParallelPort.Po
include ./$(DEPDIR)/ParallelPortPrinter.Po
include ./$(DEPDIR)/ParallelPortPrinterTest.Po
include ./$(DEPDIR)/ParallelPortTest.Po
include ./$(DEPDIR)/PollConsumer.Po
include ./$(DEPDIR)/PrintToFile.Po
include ./$(DEPDIR)/ProducerConsumerQueueTest.Po
include ./$(DEPDIR)/RTCEncoder.Po
include ./$(DEPDIR)/RTCEncoderTest.Po
include ./$(DEPDIR)/RealPackage.Po
include ./$(DEPDIR)/RemotePLC.Po
include ./$(DEPDIR)/Runnable.Po
include ./$(DEPDIR)/RunnableTest.Po
include ./$(DEPDIR)/SPM.Po
include ./$(DEPDIR)/SPMTest.Po
include ./$(DEPDIR)/SerialPort.Po
include ./$(DEPDIR)/SerialPortTest.Po
include ./$(DEPDIR)/SimpleBarCodeReader.Po
include ./$(DEPDIR)/SystemFacade.Po
include ./$(DEPDIR)/SystemFacadeTest.Po
include ./$(DEPDIR)/TestDriver.Po
include ./$(DEPDIR)/ThreadManager.Po
include ./$(DEPDIR)/TimerTest.Po
include ./$(DEPDIR)/Utils.Po
include ./$(DEPDIR)/UtilsTest.Po
include ./$(DEPDIR)/VerifyScanMPSAdapter.Po
include ./$(DEPDIR)/main.Po

distclean-depend:
	-rm -rf ./$(DEPDIR)

.cc.o:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<

.cc.obj:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `if test -f '$<'; then $(CYGPATH_W) '$<'; else $(CYGPATH_W) '$(srcdir)/$<'; fi`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=no \
#	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
#	$(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `if test -f '$<'; then $(CYGPATH_W) '$<'; else $(CYGPATH_W) '$(srcdir)/$<'; fi`

.cc.lo:
	if $(LTCXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" \
	  -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Plo"; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
#	source='$<' object='$@' libtool=yes \
#	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
#	$(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
uninstall-info-am:

ETAGS = etags
ETAGSFLAGS =

CTAGS = ctags
CTAGSFLAGS =

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$tags$$unique" \
	  || $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	     $$tags $$unique

ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkinstalldirs) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(libdir) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLIBRARIES \
	clean-libtool clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS install-libLIBRARIES

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-info-am \
	uninstall-libLIBRARIES

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libLIBRARIES clean-libtool \
	clean-noinstPROGRAMS ctags distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-binPROGRAMS install-data install-data-am \
	install-exec install-exec-am install-info install-info-am \
	install-libLIBRARIES install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-info-am uninstall-libLIBRARIES

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
